name: FirstPlugin
version: 1.0
main: be.cepseudo.first_plugin.FirstPlugin
api-version: 1.21.4
commands:
  f:
    description: Commande principale pour les factions
    usage: /f <sous-commande>
    aliases: [faction, factions]

